
informe-tp2.pdf : informe-tp2.tex 
	pdflatex -shell-escape informe-tp2.tex
	pdflatex -shell-escape informe-tp2.tex
	
clean:
	rm -v -f informe-tp2.aux informe-tp2.out informe-tp2.log
	
clean all:
	rm -v -f informe-tp2.pdf informe-tp2.aux informe-tp2.out informe-tp2.log 
